In [54]:
import pandas as pd

q1

In [55]:
pd.__version__

'3.0.5'

In [56]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")

q2

In [57]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  str
 2   fuel_type            10000 non-null  str
 3   drivetrain           10000 non-null  str
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 859.5 KB

In [58]:
records = df.shape[0]
print(records)

10000

q3

In [59]:
df['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

q4

In [103]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower               0
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

q5

In [61]:
solo_asia = df[df["origin"] == "Asia"]

In [62]:
solo_asia["fuel_efficiency_mpg"].max()

np.float64(41.2)

In [63]:
df.loc[df["origin"] == "Asia", "fuel_efficiency_mpg"].max()

np.float64(41.2)

q6

In [ ]:
df["horsepower"].median()

np.float64(254.0)

In [73]:
moda = df["horsepower"].mode()[0]
moda

np.float64(252.0)

In [74]:
df["horsepower"] = df["horsepower"].fillna(moda)

In [ ]:
df["horsepower"].median()

np.float64(252.0)

it decrease

q7

In [80]:
X = df.loc[df["origin"] == "Asia", ["vehicle_weight", "model_year"]][:7]

In [81]:
import numpy as np

In [82]:
X

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [83]:
X.T

                  2     6     8     10    15    16    22
vehicle_weight  4240  4310  4230  4420  3950  4750  4450
model_year      1996  1992  1997  1978  2007  2021  2019

In [101]:
XTX = X.T @ X

XTX_inv = np.linalg.inv(XTX)

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

w = XTX_inv @ X.T @ y

resultado_final = np.sum(w)
print(resultado_final)

0.3691969690492549